Gastronomers/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

from Gastronomers import settings

schema_view = get_schema_view(
   openapi.Info(
      title="Snippets API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)


urlpatterns = [
    url(r'^docs(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    url(r'^docs/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    url(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),


    path('user/', include('user.urls')),
    path('', include('main.urls')),
    path('', include('feed.urls')),

    path('admin/', admin.site.urls),
    path(r'auth/', include('djoser.urls')),

    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]

feed/urls.py
from django.urls import path, include, re_path
from .views import *

app_name = "Feed"

urlpatterns = [
    path('feed', feed, name="Feed"),
    path('comment', comment, name="Comment"),
    path('post-comment', post, name="Post"),
    path('follow/<int:following_id>', follow_view, name="Follow"),
    path('like/', like_view, name='Like'),
]

main/urls.py
from django.urls import path, include, re_path
from .views import *

app_name = "Main"


urlpatterns = [
    path('', index, name="Index"),
    path('restaurant/<int:id>', restaurant_view, name="Restaurant"),
]

user/urls.py
from django.urls import path

from .views import *

app_name = "User"

urlpatterns = [
    path('authenticate', entry, name="Entry"),
    path('login', login_view, name="Login"),
    path('logout', logout_view, name='Logout'),
    path('signup', signup, name='SignUp')
]

feed/models.py
from django.db import models

# Create your models here.
from main.models import Restaurant, Dish
from user.models import CustomUser


class Posts(models.Model):
    post_id = models.AutoField(primary_key=True)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    dish = models.ForeignKey(Dish, on_delete=models.CASCADE, null=True, blank=True)
    likes = models.IntegerField(default=0)
    rating = models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], blank=True, null=True)
    shares = models.IntegerField(default=0, blank=True, null=True)
    caption = models.TextField()
    posted_date = models.DateTimeField(auto_now=True)
    pic = models.ImageField(blank=True, null=True, upload_to='media')


class Pictures(models.Model):
    picture_id = models.AutoField(primary_key=True)
    post = models.ForeignKey(Posts, on_delete=models.CASCADE)
    picture = models.ImageField()


class Comments(models.Model):
    comment_id = models.AutoField(primary_key=True)
    post = models.ForeignKey(Posts, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    body = models.TextField()

feed/forms.py
from django import forms

from feed.models import Posts
from main.models import Restaurant


class PostForm(forms.ModelForm):
    restaurant = forms.ModelChoiceField(queryset=Restaurant.objects.all())

    class Meta:
        model = Posts
        fields = ('restaurant', 'pic', 'caption')

feed/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

# Create your views here.
from feed.forms import PostForm
from feed.models import Posts, Comments
from main.models import Restaurant
from user.models import CustomUser, Follows


@login_required()
def feed(request):
    user = CustomUser.objects.get(username=request.user.username)
    following = Follows.objects.filter(follower=user).count()
    followers = Follows.objects.filter(following=user).count()
    post_list = Posts.objects.order_by('-posted_date')[:5]
    restaurants = Restaurant.objects.all()
    post_form = PostForm()
    return render(request, 'feed.html',
                  {'user': user, 'following': following, 'followers': followers, 'post_list': post_list,
                   'restaurants': restaurants, 'post_form': post_form})


@login_required()
def comment(request):
    if request.method == 'POST':
        post = Posts.objects.get(post_id=request.POST['post_id'])
        body = request.POST['body']

        com = Comments(post=post, body=body, user=request.user)
        com.save()
        messages.success(request, "Your comment has been added")
        return redirect('Feed:Feed')


@login_required()
def post(request):
    if request.method == 'POST':
        post_data = PostForm(request.POST, request.FILES)
        if post_data.is_valid():
            pos = post_data.save(commit=False)
            pos.user = request.user
            pos.save()
            messages.success(request, "Your post has been uploaded")
            return redirect('Feed:Feed')
        else:
            messages.error(request, "There is an error in the post, please try again")
            return redirect('Feed:Feed')


@login_required()
def follow_view(request, **kwargs):
    following = CustomUser.objects.get(account_id=kwargs['following_id'])
    follower = request.user
    if following == follower:
        messages.error(request, "You cannot follow yourself")
        return redirect('Feed:Feed')

    fol = Follows(following=following, follower=follower)
    fol.save()
    messages.success(request, f"You are now following {following.username}")
    return redirect('Feed:Feed')


@login_required()
def like_view(request):
    post = Posts.objects.get(post_id=request.POST['post_id'])
    post.likes += 1
    post.save()
    messages.success(request, "You liked a post")
    return redirect('Feed:Feed')

templates/index.html
<!--DEVELOPED BY ---
    _HEETARTHI KAMDAR_
17BCE0132-->

<html lang="en">
{% load staticfiles %}
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Abbiocco</title>
    <link rel="shortcut icon" href=" {% static 'images/icon.ico' %} ">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" media="screen" href=" {% static 'css/style.css' %} " />
</head>
<body>
   <div class="fixed-top" >
        <div class="social-container">
            <div class="navbar">
                <img src=" {% static 'images/logo.png' %} " class="logo" href="#section1" alt="">
                <div class="social-icons">
                    <ul>
                <li><a href="https://www.instagram.com/abbiocco.adroitalliance/" target="_blank"><em class="fa fa-instagram"></em></a></li>
                <li><a href="https://www.facebook.com/abbiocco.adroitalliance/" target="_blank"><em class="fa fa-facebook"></em></a></li>
                <li><a href="mailto:abbiocco.adroitalliance@gmail.com?Subject=Feedback%20Form" target="_top"><em class="fa fa-envelope-o"></em></a></li>
                        </ul>
                </div>
            </div>
        </div>
    </div>
    <section id="section1" class="cd-section1">
        <br><br>
        <h1>WHERE'S THE FOOD?</h1><br><br>
        <img src=" {% static 'images/cheeseburger.png' %} " alt="Cheeseburger" class="hero">
</section>


<div class="row">
    <div class="column" style="background-color:white;">
        <div class="centered">
        <img class="img3" src=" {% static 'images/dualphone1.png' %} " alt="dual phone">
    </div>
</div>
    <div class="column" s tyle="background-color:rgb(255, 255, 255);">
        <div class="centered">
            <h2>Review <br> restaurants</h2></div>
    </div>
  </div>
  
  
  
  
  <div class="row">
    <div class="column" style="background-color:#fbce33;">
        <div class="centered">
            <h4>Rate your <br>Fav dishes</h4></div>
    </div>
    <div class="column" style="background-color:#fbce33;">
        <div class="centered">
            <img class="img3" src=" {% static 'images/dualphone2.png' %} " alt="dual phone"><br>
        </div>
    </div>
  </div>

  <section id="section4">
      
    <div class="centered">
            <h3>BON APPETIT</h3><br>
            <a href=" {% url 'User:Entry' %} "><button class="btn third">Get Started</button></a>
        <br><img class="img2" src=" {% static 'images/half2.png' %} " alt="mockup phone"><br><br>
        <footer class="my-5 text-center">
                <!-- Copyright removal is not prohibited! -->
                <a style="font-family:Helvica"><b style="font-size:13px;">COPYRIGHT © 2019. ALL RIGHTS RESERVED.</b></a>
        <br>
                <small><div class="marg">
                    <a style="font-family:Helvica; font-size:10px;" href="" class="m-2"><b>PRIVACY POLICY</b></a>  #  todo add a privacy page
                </div></small>
            </footer>
 </div>
 </section>

</body>
</html>

templates/login.html
<!--DEVELOPED BY ---
    _HEETARTHI KAMDAR_
CEO - ADROIT ALLIANCE-->
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Abbiocco | Login</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href=" {% static 'images/icon.ico' %} ">

    <meta name="description" content=""/>
    <meta name="keywords" content=""/>
    <link rel="stylesheet" type="text/css" href=" {% static 'css/animate.css' %} ">
    <link rel="stylesheet" type="text/css" href=" {% static 'css/bootstrap.min.css' %} ">
    <link rel="stylesheet" type="text/css" href=" {% static 'css/line-awesome.css' %} ">
    <link rel="stylesheet" type="text/css" href=" {% static 'css/line-awesome-font-awesome.min.css' %} ">
    {#	<link href=" {% static 'vendor/fontawesome-free/css/all.min.css' %} " rel="stylesheet" type="text/css">#}
    {#	<link rel="stylesheet" type="text/css" href=" {% static 'css/font-awesome.min.css' %} ">#}
    <link rel="stylesheet" type="text/css" href=" {% static 'css/slick.css' %} ">
    <link rel="stylesheet" type="text/css" href=" {% static 'css/slick-theme.css' %} ">
    <link rel="stylesheet" type="text/css" href=" {% static 'css/style1.css' %} ">
    <link rel="stylesheet" type="text/css" href=" {% static 'css/responsive.css' %} ">
</head>


<body class="sign-in" oncontextmenu="return false;">

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}


<div class="wrapper">

    <div class="sign-in-page">
        <div class="signin-popup">
            <div class="signin-pop">
                <div class="row">
                    <div class="col-lg-6">
                        <div class="cmp-info">
                            <div class="cm-logo">
                                <img src=" {% static 'images/logo.png' %} " alt="">
                                <p>Abbiocco is a dedicated platform that allows users to enhance their culinary
                                    experiences.
                                    With the key feature of sharing of your food and restaurant reviews, Abbiocco
                                    helps the users to share whatever information they have about a particular
                                    restaurant to the fellow users especially in means of photograph sharing like social
                                    media and reviews.
                                    A user can, through the photograph, enter the restaurant page where they can view
                                    other information like address and menu.</p>
                            </div>
                            <img src=" {% static 'images/cheeseburger.png' %} " alt="">
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="login-sec">
                            <ul class="sign-control">
                                <li data-tab="tab-1" class="current"><a href="#" title="">Sign in</a></li>
                                <li data-tab="tab-2"><a href="#" title="">Sign up</a></li>
                            </ul>
                            <div class="sign_in_sec current" id="tab-1">

                                <h3>Sign in</h3>
                                <form method="post" action="{% url 'User:Login' %}">
                                    {% csrf_token %}
                                    <div class="row">
                                        <div class="col-lg-12 no-pdd">
                                            <div class="sn-field">
                                                <em class="fa fa-user"></em>
                                                <input type="text" name="username" placeholder="Username">
                                            </div><!--sn-field end-->
                                        </div>
                                        <div class="col-lg-12 no-pdd">
                                            <div class="sn-field">
                                                <em class="fa fa-lock"></em>
                                                <input type="password" name="password" placeholder="Password">
                                            </div>
                                        </div>

                                        <div class="col-lg-12 no-pdd">
                                            <input type="submit" value="Sign In">
                                        </div>
                                    </div>
                                </form>

                            </div><!--sign_in_sec end-->
                            <div class="sign_in_sec" id="tab-2">

                                <div class="dff-tab current" id="tab-3">
                                    <form method="post" action="{% url 'User:SignUp' %}">
                                        {% csrf_token %}
                                        <div class="row">
                                            <div class="col-lg-12 no-pdd">
                                                <div class="sn-field">
                                                    <em class="fa fa-user"></em>
                                                    <input type="text" name="name" placeholder="Full Name">
                                                </div>
                                            </div>

                                            <div class="col-lg-12 no-pdd">
                                                <div class="sn-field">
                                                    <em class="fa fa-user"></em>
                                                    <input type="text" name="username" placeholder="User Name">
                                                </div>
                                            </div>

                                            <div class="col-lg-12 no-pdd">
                                                <div class="sn-field">
                                                    <em class="fa fa-envelope"></em>
                                                    <input type="email" name="email" placeholder="Email">
                                                </div>
                                            </div>
                                            <div class="col-lg-12 no-pdd">
                                                <div class="sn-field">
                                                    <em class="fa fa-lock"></em>
                                                    <input type="password" name="password" placeholder="Password">
                                                </div>
                                            </div>


                                            <div class="col-lg-12 no-pdd">
                                                <input type="submit" value="Get Started">
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>

        </div>


    </div>


</div>


<script type="text/javascript" src=" {% static 'js/jquery.min.js' %} "></script>
<script type="text/javascript" src=" {% static 'js/popper.js' %} "></script>
<script type="text/javascript" src=" {% static 'js/bootstrap.min.js' %} "></script>
<script type="text/javascript" src=" {% static 'js/slick.min.js' %} "></script>
<script type="text/javascript" src=" {% static 'js/script.js' %} "></script>
</body>
</html>

templates/restaurant.html
<!--DEVELOPED BY ---
    _HEETARTHI KAMDAR_
17BCE0132-->



<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">

<head>
	<meta charset="UTF-8">
	<title>Abbiocco - Restaurant</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="" />
	<meta name="keywords" content="" />
	<link rel="stylesheet" type="text/css" href=" {% static 'css/animate.css' %} ">
	<link rel="stylesheet" type="text/css" href=" {% static 'css/bootstrap.min.css' %} ">
{#	<link rel="stylesheet" type="text/css" href=" {% static 'css/flatpickr.min.css' %} ">#}
	<link rel="stylesheet" type="text/css" href=" {% static 'css/line-awesome.css' %} ">
	<link rel="stylesheet" type="text/css" href=" {% static 'css/line-awesome-font-awesome.min.css' %} ">
{#	<link href=" {% static 'vendor/fontawesome-free/css/all.min.css' %} " rel="stylesheet" type="text/css">#}
{#	<link rel="stylesheet" type="text/css" href=" {% static 'css/font-awesome.min.css' %} ">#}
	<link rel="stylesheet" type="text/css" href=" {% static 'css/slick.css' %} ">
	<link rel="stylesheet" type="text/css" href=" {% static 'css/slick-theme.css' %} ">
	<link rel="stylesheet" type="text/css" href=" {% static 'css/style1.css' %} ">
	<link rel="stylesheet" type="text/css" href=" {% static 'css/responsive.css' %} ">
</head>


<body oncontextmenu="return false;">

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

	<div class="wrapper">

		<header>
			<div class="container">
				<div class="header-data">

{#					<div class="search-bar">#}
{#						<form method="post" action="{% url 'Main:Search' %}">#}
{#							<input type="text" name="search" placeholder="Search...">#}
{#							<input type="submit"><em class="fa fa-search"></em>#}
{#						</form>#}
{#					</div>#}

					<nav>
						<ul>
							<li>
                                {% if user.is_authenticated %}
								<a href=" {% url 'Feed:Feed' %} " title="">
									<span><img src=" {% static 'images/icon1.png' %} " alt=""></span>
									Home
                                </a>
                                {% else %}
                                <a href=" {% url 'Main:Index' %} " title="">
									<span><img src=" {% static 'images/icon1.png' %} " alt=""></span>
									Home
                                </a>
                                {% endif %}

							</li>
						</ul>
					</nav>
				</div>
			</div>
		</header>

		<main>
			<div class="main-section">
				<div class="container">
					<div class="main-section-data">
						<div class="row">
							<div class="col-lg-3">
								<div class="main-left-sidebar">
									<div class="user_profile">
										<div class="user-pro-img">
											<img src=" {% static 'images/resources/company-profile.png' %} " alt="">
										</div>

										<div class="user_pro_status">
											<h3>
                                                {% if not restaurant.logo %}
												<img src=" {% static 'images/adv2.jpg' %} " alt="">
												{% else %}
                                                <img src="{{ restaurant.logo.url}}" alt="">
                                                {% endif %}
											</h3>
										</div>

										<ul class="social_links">
											<li><a href="#" title=""><em class="fa fa-pinterest"></em>
													{{ restaurant.pintrest }}</a></li>
											<li><a href="#" title=""><em class="fa fa-instagram"></em>
													{{ restaurant.instagram }}</a></li>
											<li><a href="#" title=""><em class="fa fa-youtube"></em>
													{{ restaurant.youtube }}</a></li>
										</ul>
									</div>

									


								</div>

							</div>
							<div class="col-lg-6">
								<div class="main-ws-sec">
									<div class="user-tab-sec">
										<h3>{{ restaurant.name }}</h3>
										<div class="star-descp">
											<span>Established Since {{ restaurant.establishment_year }}</span>
											<ul>
                                                {% for i in n %}
												<li><em class="fa fa-star"></em></li>
                                                {% endfor %}
    										</ul>
										</div>

										<div class="tab-feed">
											<ul>

												<li data-tab="info-dd" class="active">
													<a href="#" title="">
														<img src=" {% static 'images/ic2.png' %} " alt="">
														<span>Info</span>
													</a>
												</li>


											</ul>
										</div>
									</div>


									<div class="product-feed-tab current" id="info-dd">
										<div class="user-profile-ov">
											<h3>Over View</h3>
											<p>{{ restaurant.overview }}</p>
										</div>

									</div>
								</div>
							</div>


							<div class="col-lg-3">
								<div class="right-sidebar">
									<div class="widget widget-about">
										<img src=" {% static 'images/adv1.jpg' %} " alt="">

									</div>
									<div class="widget widget-about">
										<img src=" {% static 'images/adv2.jpg' %} " alt="">

									</div>
								</div>

							</div>
						</div>
					</div>
				</div>
			</div>
		</main>
	</div>


	<script type="text/javascript" src=" {% static 'js/jquery.min.js' %} "></script>
	<script type="text/javascript" src=" {% static 'js/popper.js' %} "></script>
	<script type="text/javascript" src=" {% static 'js/bootstrap.min.js' %} "></script>
{#	<script type="text/javascript" src=" {% static 'js/flatpickr.min.js' %} "></script>#}
	<script type="text/javascript" src=" {% static 'js/slick.min.js' %} "></script>
	<script type="text/javascript" src=" {% static 'js/script.js' %} "></script>
</body>

</html>